// Seed data for PawFinder. Coordinates are percentages (0-100) on the stylized map.
// Designed so several lost/found reports are strong matches, for a compelling demo.
window.PAWFINDER_SEED = [
  {
    id: "mochi",
    status: "lost",
    name: "Mochi",
    species: "Dog",
    breed: "Shiba Inu",
    color: "Tan & white",
    description: "Very shy, wearing a red harness. Runs from strangers but comes for treats. Microchipped.",
    area: "Maple Park",
    date: "2026-07-06",
    contact: "text 555-0142",
    photo: null,
    emoji: "🐕",
    x: 28, y: 34,
  },
  {
    id: "found-shiba",
    status: "found",
    name: "",
    species: "Dog",
    breed: "Shiba / spitz type",
    color: "Tan and white",
    description: "Small tan dog with curly tail hiding under the bandstand. Red harness, no tag. Skittish.",
    area: "Maple Park bandstand",
    date: "2026-07-08",
    contact: "call 555-0987",
    photo: null,
    emoji: "🐕",
    x: 33, y: 41,
  },
  {
    id: "luna",
    status: "lost",
    name: "Luna",
    species: "Cat",
    breed: "Domestic shorthair",
    color: "Grey tabby",
    description: "Indoor cat, slipped out a window. Green eyes, small notch in left ear. Answers to Luna.",
    area: "Riverside & 4th",
    date: "2026-07-07",
    contact: "text 555-0231",
    photo: null,
    emoji: "🐈",
    x: 63, y: 58,
  },
  {
    id: "found-tabby",
    status: "found",
    name: "",
    species: "Cat",
    breed: "Shorthair tabby",
    color: "Grey striped",
    description: "Friendly grey tabby hanging around the laundromat, notched ear. Been fed by neighbors.",
    area: "Riverside Ave",
    date: "2026-07-09",
    contact: "DM @riverside_helper",
    photo: null,
    emoji: "🐈",
    x: 68, y: 52,
  },
  {
    id: "kiwi",
    status: "lost",
    name: "Kiwi",
    species: "Bird",
    breed: "Green-cheek conure",
    color: "Green & red",
    description: "Escaped during cage cleaning. Whistles the first bars of a lullaby. Very tame, will step up.",
    area: "Oakridge Lane",
    date: "2026-07-05",
    contact: "call 555-0777",
    photo: null,
    emoji: "🦜",
    x: 46, y: 20,
  },
  {
    id: "buddy",
    status: "reunited",
    name: "Buddy",
    species: "Dog",
    breed: "Golden Retriever",
    color: "Golden",
    description: "Reunited after 3 days thanks to a neighbor's sighting! Thank you PawFinder community. 💛",
    area: "Elm Street",
    date: "2026-07-02",
    contact: "—",
    photo: null,
    emoji: "🐕",
    x: 18, y: 68,
  },
  {
    id: "found-rabbit",
    status: "found",
    name: "",
    species: "Rabbit",
    breed: "Lop",
    color: "White & brown",
    description: "Lop-eared bunny nibbling in a community garden bed. Well-fed, clearly someone's pet.",
    area: "Sunnyside Community Garden",
    date: "2026-07-09",
    contact: "text 555-0654",
    photo: null,
    emoji: "🐇",
    x: 80, y: 30,
  },
  {
    id: "pepper",
    status: "lost",
    name: "Pepper",
    species: "Dog",
    breed: "Border Collie mix",
    color: "Black & white",
    description: "High-energy, wearing a blue bandana. Loves to chase balls. May follow joggers.",
    area: "Riverside Trail",
    date: "2026-07-08",
    contact: "text 555-0490",
    photo: null,
    emoji: "🐕",
    x: 55, y: 72,
  },
];
